image: php:8.2-alpine

stages:
  - build
  - test

composer:
  stage: build
  image: composer:2.5
  script:
    - composer install --dev
  artifacts:
    paths:
      - vendor/
  cache:
    paths:
      - vendor/

test:
  stage: test
  cache:
    paths:
      - vendor
  script:
    - vendor/bin/phpunit tests/
  dependencies:
    - composer
